-- ============================================================
-- COMPLETE E-COMMERCE DATABASE SCHEMA
-- Run this ENTIRE file in Supabase SQL Editor (Dashboard > SQL Editor > New Query)
-- ============================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- 1. PROFILES TABLE (Auto-created on user signup)
-- ============================================================
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  avatar_url TEXT,
  phone TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Function to auto-create profile on signup
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO profiles (id, full_name)
  VALUES (NEW.id, NEW.raw_user_meta_data->>'full_name')
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for auto-profile creation
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- ============================================================
-- 2. PRODUCTS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  original_price DECIMAL(10,2),
  image TEXT NOT NULL,
  images TEXT[] DEFAULT '{}',
  category TEXT NOT NULL,
  brand TEXT DEFAULT 'VikaStore',
  stock INTEGER DEFAULT 100,
  rating DECIMAL(3,2) DEFAULT 0,
  review_count INTEGER DEFAULT 0,
  tags TEXT[] DEFAULT '{}',
  is_featured BOOLEAN DEFAULT false,
  is_on_sale BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================
-- 3. ADDRESSES TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS addresses (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  full_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  address_line1 TEXT NOT NULL,
  address_line2 TEXT,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  pincode TEXT NOT NULL,
  is_default BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================
-- 4. ORDERS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS orders (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  address_id UUID REFERENCES addresses(id) ON DELETE SET NULL,
  total_amount DECIMAL(10,2) NOT NULL,
  status TEXT DEFAULT 'confirmed' CHECK (status IN ('confirmed', 'processing', 'shipped', 'delivered', 'cancelled')),
  payment_status TEXT DEFAULT 'paid' CHECK (payment_status IN ('paid', 'unpaid', 'refunded')),
  payment_method TEXT DEFAULT 'card',
  tracking_id TEXT DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================
-- 5. ORDER ITEMS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id UUID REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  quantity INTEGER NOT NULL,
  price_at_time DECIMAL(10,2) NOT NULL
);

-- ============================================================
-- 6. REVIEWS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS reviews (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  rating INTEGER CHECK (rating BETWEEN 1 AND 5) NOT NULL,
  title TEXT,
  body TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(product_id, user_id)
);

-- ============================================================
-- 7. WISHLISTS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS wishlists (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, product_id)
);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE wishlists ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Public products readable" ON products;
DROP POLICY IF EXISTS "Anyone can read products" ON products;
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON products;
DROP POLICY IF EXISTS "Users can insert their own orders." ON orders;
DROP POLICY IF EXISTS "Users can view their own orders." ON orders;
DROP POLICY IF EXISTS "Users can insert their own order items." ON order_items;
DROP POLICY IF EXISTS "Users can view their own order items." ON order_items;

-- PROFILES
CREATE POLICY "Users can view any profile" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- PRODUCTS (public read, admin write)
CREATE POLICY "Products are publicly readable" ON products FOR SELECT USING (true);
CREATE POLICY "Authenticated users can insert products" ON products FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can update products" ON products FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can delete products" ON products FOR DELETE USING (auth.role() = 'authenticated');

-- ADDRESSES
CREATE POLICY "Users can manage own addresses" ON addresses FOR ALL USING (auth.uid() = user_id);

-- ORDERS
CREATE POLICY "Users can insert own orders" ON orders FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view own orders" ON orders FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update own orders" ON orders FOR UPDATE USING (auth.uid() = user_id);

-- ORDER ITEMS
CREATE POLICY "Users can insert own order items" ON order_items FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM orders WHERE orders.id = order_items.order_id AND orders.user_id = auth.uid())
);
CREATE POLICY "Users can view own order items" ON order_items FOR SELECT USING (
  EXISTS (SELECT 1 FROM orders WHERE orders.id = order_items.order_id AND orders.user_id = auth.uid())
);

-- REVIEWS
CREATE POLICY "Reviews are publicly readable" ON reviews FOR SELECT USING (true);
CREATE POLICY "Authenticated users can insert reviews" ON reviews FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own reviews" ON reviews FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own reviews" ON reviews FOR DELETE USING (auth.uid() = user_id);

-- WISHLISTS
CREATE POLICY "Users can manage own wishlist" ON wishlists FOR ALL USING (auth.uid() = user_id);

-- ============================================================
-- FUNCTION TO UPDATE PRODUCT RATING AUTOMATICALLY
-- ============================================================
CREATE OR REPLACE FUNCTION update_product_rating()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE products SET
    rating = (SELECT AVG(rating) FROM reviews WHERE product_id = COALESCE(NEW.product_id, OLD.product_id)),
    review_count = (SELECT COUNT(*) FROM reviews WHERE product_id = COALESCE(NEW.product_id, OLD.product_id))
  WHERE id = COALESCE(NEW.product_id, OLD.product_id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_review_change ON reviews;
CREATE TRIGGER on_review_change
  AFTER INSERT OR UPDATE OR DELETE ON reviews
  FOR EACH ROW EXECUTE FUNCTION update_product_rating();

-- ============================================================
-- SEED DATA - PRODUCTS (20 realistic products)
-- ============================================================
INSERT INTO products (name, description, price, original_price, image, images, category, brand, stock, is_featured, is_on_sale, tags) VALUES
(
  'Sony WH-1000XM5 Wireless Headphones',
  'Industry-leading noise cancellation with 30-hour battery life, crystal clear hands-free calling, and exceptional sound quality. Perfect for work and travel.',
  24999, 32999,
  'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
  'Electronics', 'Sony', 85, true, true,
  ARRAY['headphones', 'wireless', 'noise-cancelling', 'sony']
),
(
  'Apple Watch Series 9',
  'Advanced health features including blood oxygen sensor, ECG, crash detection, and 18-hour battery. Water resistant up to 50 meters.',
  41900, 44900,
  'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80'],
  'Electronics', 'Apple', 50, true, false,
  ARRAY['smartwatch', 'apple', 'wearable', 'fitness']
),
(
  'Herman Miller Aeron Chair',
  'Ergonomic office chair with PostureFit SL back support, 8Z Pellicle suspension, and fully adjustable armrests. Built for all-day comfort.',
  89000, 99000,
  'https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?auto=format&fit=crop&w=800&q=80'],
  'Furniture', 'Herman Miller', 20, false, false,
  ARRAY['chair', 'ergonomic', 'office', 'herman-miller']
),
(
  'Keychron K2 Mechanical Keyboard',
  'Wireless mechanical keyboard with hot-swappable switches, RGB backlight, and compact 75% layout. Compatible with Mac and Windows.',
  8999, 10999,
  'https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=800&q=80'],
  'Electronics', 'Keychron', 200, true, true,
  ARRAY['keyboard', 'mechanical', 'wireless', 'rgb']
),
(
  'LG 27UK850 4K Monitor',
  '27-inch UHD IPS Display with HDR10, USB-C connectivity, and AMD FreeSync. Perfect for creative professionals and gamers.',
  34999, 42999,
  'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80'],
  'Electronics', 'LG', 45, false, true,
  ARRAY['monitor', '4k', 'uhd', 'lg']
),
(
  'Logitech MX Master 3S Mouse',
  'Advanced wireless mouse with ultra-fast MagSpeed electromagnetic scrolling, 8K DPI sensor, and whisper-quiet clicks.',
  9995, 11995,
  'https://images.unsplash.com/photo-1625723044792-47eb3abd4e71?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1625723044792-47eb3abd4e71?auto=format&fit=crop&w=800&q=80'],
  'Electronics', 'Logitech', 180, true, false,
  ARRAY['mouse', 'wireless', 'logitech', 'mx-master']
),
(
  'Ember Temperature Control Mug',
  'Smart mug that maintains your perfect drinking temperature from 50-62.5°C for up to 80 minutes. Controlled via smartphone app.',
  11999, 14999,
  'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=800&q=80'],
  'Accessories', 'Ember', 100, false, false,
  ARRAY['mug', 'smart', 'coffee', 'ember']
),
(
  'Peak Design Everyday Backpack 20L',
  'The most versatile everyday carry bag with FlexFold dividers, magnetic closure, and weatherproof 400D nylon canvas.',
  22000, 25000,
  'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80'],
  'Accessories', 'Peak Design', 60, false, false,
  ARRAY['backpack', 'bag', 'peak-design', 'everyday']
),
(
  'Anker 737 Power Bank 24000mAh',
  'High-capacity portable charger with 140W max output, smart display, and bi-directional USB-C charging for laptops and phones.',
  7999, 9999,
  'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=800&q=80'],
  'Electronics', 'Anker', 300, true, true,
  ARRAY['powerbank', 'charger', 'anker', 'portable']
),
(
  'IKEA MALM Desk',
  'Clean-lined study desk with cable management hole, easy assembly, and robust particleboard construction.',
  8999, 11999,
  'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800&q=80'],
  'Furniture', 'IKEA', 40, false, true,
  ARRAY['desk', 'study', 'ikea', 'malm', 'furniture']
),
(
  'Philips Hue Smart LED Bulb Starter Kit',
  'Control 4 color-changing smart bulbs with Hue Bridge via app, voice, or sensor. 16 million colors, routines and automation.',
  8499, 10999,
  'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
  'Electronics', 'Philips', 120, false, false,
  ARRAY['smart-home', 'bulb', 'philips', 'hue', 'lighting']
),
(
  'Moleskine Classic Notebook Large',
  'Hard cover ruled notebook with 240 pages of acid-free, fountain pen friendly paper. A timeless tool for creativity.',
  999, 1299,
  'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80'],
  'Accessories', 'Moleskine', 500, false, false,
  ARRAY['notebook', 'moleskine', 'stationery', 'journal']
),
(
  'Jabra Evolve2 75 Business Headset',
  'Professional wireless headset with 8-mic call technology, active noise cancellation, and Teams/Zoom certification.',
  29999, 35999,
  'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
  'Electronics', 'Jabra', 70, false, false,
  ARRAY['headset', 'business', 'jabra', 'wireless']
),
(
  'Xiaomi Smart Band 8',
  'Fitness tracker with 1.62" AMOLED display, 16-day battery, 150+ workout modes, SpO2 and heart rate monitoring.',
  2999, 3999,
  'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?auto=format&fit=crop&w=800&q=80'],
  'Electronics', 'Xiaomi', 400, true, true,
  ARRAY['fitness-band', 'xiaomi', 'wearable', 'health']
),
(
  'Bellroy Note Sleeve Wallet',
  'Slim, RFID-protected leather wallet that holds 2-12 cards plus notes. Crafted from premium, responsibly sourced leather.',
  4999, 6500,
  'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80'],
  'Accessories', 'Bellroy', 150, false, false,
  ARRAY['wallet', 'leather', 'bellroy', 'rfid', 'slim']
),
(
  'Kindle Paperwhite (2023)',
  '6.8" display with adjustable warm light, waterproof (IPX8), 16GB storage, and weeks-long battery life.',
  14999, 17999,
  'https://images.unsplash.com/photo-1592496001020-d31bd830651f?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1592496001020-d31bd830651f?auto=format&fit=crop&w=800&q=80'],
  'Electronics', 'Amazon', 250, true, false,
  ARRAY['kindle', 'ebook', 'reading', 'amazon']
),
(
  'Bose QuietComfort Earbuds II',
  'World''s best noise cancelling earbuds with CustomTune technology, personalized audio, and 6-hour battery per charge.',
  26900, 29900,
  'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=800&q=80'],
  'Electronics', 'Bose', 90, true, false,
  ARRAY['earbuds', 'bose', 'noise-cancelling', 'wireless']
),
(
  'Levi''s 511 Slim Jeans',
  'Classic slim fit jeans in authentic stretch denim. Sits below waist, slim through thigh and leg opening.',
  3999, 5999,
  'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=800&q=80'],
  'Fashion', 'Levi''s', 300, false, true,
  ARRAY['jeans', 'levis', 'fashion', 'denim', 'slim-fit']
),
(
  'Nike Air Max 270',
  'The Nike Air Max 270 delivers remarkable comfort with its Max Air unit in the heel. Lightweight mesh upper with foam midsole.',
  12995, 14995,
  'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
  'Fashion', 'Nike', 180, true, false,
  ARRAY['shoes', 'nike', 'air-max', 'sneakers', 'running']
),
(
  'Corsair K95 RGB Platinum Gaming Keyboard',
  'Premium gaming mechanical keyboard with Cherry MX Speed switches, 19-key rollover anti-ghosting, and dedicated macro keys.',
  15999, 19999,
  'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80'],
  'Electronics', 'Corsair', 60, false, true,
  ARRAY['gaming', 'keyboard', 'rgb', 'corsair', 'mechanical']
);

-- ============================================================
-- Done! All tables, RLS policies, triggers and seed data created.
-- ============================================================
